import { BonusItem, FaqItem, PricingPlan, RelatoImageItem } from '../types';

export const HERO_DATA = {
  badge: 'Método aprovado por mais de 10.000 famílias',
  headline: 'Ajude seu filho a desenvolver uma leitura mais fluente, semana após semana.',
  subheadline: 'Atividades práticas para crianças de 4 a 10 anos exercitarem letras, sílabas, palavras e leitura de maneira leve, aprenda até 3x mais rápido.',
  ctaText: 'QUERO QUE MEU FILHO APRENDA',
  secondaryCtaText: 'Ver o que vem no Kit',
  benefits: [
    { id: '1', text: 'Método aprovado por pais e mães' },
    { id: '2', text: 'Ideal para ensinos pedagógicos' },
    { id: '3', text: 'Acesso imediato após a compra' },
  ],
  statsBadge: 'Ideal para rotinas a partir de 15 minutos ao dia',
};

export const QUICK_BENEFITS = [
  {
    id: 'b1',
    emoji: '🤦',
    solutionEmoji: '💡',
    title: 'Dificuldade em juntar as sílabas',
    description: 'Dificuldade em juntar as sílabas e formar palavras (consciência fonológica)',
    solution: 'Usar jogos de rima, aliteração e cantigas de roda (como as que já te passei!) para treinar o ouvido antes de exigir a leitura formal — a música prepara o cérebro pra decodificar sons.',
    bgTone: 'bg-[#EFF6FF]',
    borderTone: 'border-[#DBEAFE]',
    textColor: 'text-[#1E40AF]',
    solutionTextColor: 'text-[#1D4ED8]',
    iconBg: 'bg-[#DBEAFE]',
    imageFront: 'https://i.imgur.com/kOqWs9h.png',
    imageBack: 'https://i.imgur.com/2dMc2OC.png',
  },
  {
    id: 'b2',
    emoji: '🤯',
    solutionEmoji: '💡',
    title: 'Desmotivação & Resistência',
    description: 'Desmotivação e resistência na hora de estudar',
    solution: 'Transformar a alfabetização em brincadeira (caça-palavras, teatro de fantoches, histórias criadas em conjunto) — criança aprende melhor brincando do que sendo forçada a decorar.',
    bgTone: 'bg-[#FDF2F8]',
    borderTone: 'border-[#FCE7F3]',
    textColor: 'text-[#9D174D]',
    solutionTextColor: 'text-[#BE185D]',
    iconBg: 'bg-[#FCE7F3]',
    imageFront: 'https://i.imgur.com/1Q25FzJ.png',
    imageBack: 'https://i.imgur.com/kjtEsfz.png',
  },
  {
    id: 'b3',
    emoji: '😰',
    solutionEmoji: '💡',
    title: 'Comparação com outras crianças',
    description: 'Comparação com outras crianças da mesma idade',
    solution: 'Focar na evolução individual da criança (registrar pequenos avanços semana a semana) em vez de comparar com a turma — respeitar o ritmo evita bloqueios emocionais que atrasam ainda mais o processo.',
    bgTone: 'bg-[#FEFCE8]',
    borderTone: 'border-[#FEF08A]',
    textColor: 'text-[#854D0E]',
    solutionTextColor: 'text-[#B45309]',
    iconBg: 'bg-[#FEF08A]',
    imageFront: 'https://i.imgur.com/ANoSSQj.png',
    imageBack: 'https://i.imgur.com/tU4GGxY.png',
  },
  {
    id: 'b4',
    emoji: '😤',
    solutionEmoji: '💡',
    title: 'Falta de Foco & Atenção',
    description: 'Dificuldade em manter o foco e a atenção durante a leitura',
    solution: 'Reduzir o tempo de cada sessão (5 a 10 minutos focados valem mais que 30 minutos forçados), eliminar distrações no ambiente e intercalar leitura com movimento físico entre as atividades.',
    bgTone: 'bg-[#F0FDF4]',
    borderTone: 'border-[#DCFCE7]',
    textColor: 'text-[#166534]',
    solutionTextColor: 'text-[#15803D]',
    iconBg: 'bg-[#DCFCE7]',
    imageFront: 'https://i.imgur.com/aiSvm0l.png',
    imageBack: 'https://i.imgur.com/TYGfnvM.png',
  },
];

export const INSIDE_LOOK_SLIDES = [
  {
    id: 'inside-1',
    imageUrl: 'https://i.imgur.com/8U7Xc9K.png',
    alt: 'Atividade 1',
  },
  {
    id: 'inside-2',
    imageUrl: 'https://i.imgur.com/56Q2n7b.png',
    alt: 'Atividade 2',
  },
  {
    id: 'inside-3',
    imageUrl: 'https://i.imgur.com/dGYR7iz.png',
    alt: 'Atividade 3',
  },
  {
    id: 'inside-4',
    imageUrl: 'https://i.imgur.com/mE7beVE.png',
    alt: 'Atividade 4',
  },
  {
    id: 'inside-5',
    imageUrl: 'https://i.imgur.com/tSiy2vB.png',
    alt: 'Atividade 5',
  },
  {
    id: 'inside-6',
    imageUrl: 'https://i.imgur.com/z2czkes.png',
    alt: 'Atividade 6',
  },
  {
    id: 'inside-7',
    imageUrl: 'https://i.imgur.com/J1F3Z7Y.png',
    alt: 'Atividade 7',
  },
  {
    id: 'inside-8',
    imageUrl: 'https://i.imgur.com/TWarkkp.png',
    alt: 'Atividade 8',
  },
];

export const GALLERY_ROW_TOP = [
  { id: 'top-1', url: 'https://i.imgur.com/Qv2YQnX.jpeg', title: 'Atividade 1' },
  { id: 'top-2', url: 'https://i.imgur.com/A0H4iC8.jpeg', title: 'Atividade 2' },
  { id: 'top-3', url: 'https://i.imgur.com/bIrWXnR.jpeg', title: 'Atividade 3' },
  { id: 'top-4', url: 'https://i.imgur.com/PCbw8Va.jpeg', title: 'Atividade 4' },
  { id: 'top-5', url: 'https://i.imgur.com/DtLyf4f.jpeg', title: 'Atividade 5' },
  { id: 'top-6', url: 'https://i.imgur.com/EzQiRh9.jpeg', title: 'Atividade 6' },
  { id: 'top-7', url: 'https://i.imgur.com/ENELXMF.jpeg', title: 'Atividade 7' },
  { id: 'top-8', url: 'https://i.imgur.com/025FMkw.jpeg', title: 'Atividade 8' },
  { id: 'top-9', url: 'https://i.imgur.com/8vgVk7e.jpeg', title: 'Atividade 9' },
  { id: 'top-10', url: 'https://i.imgur.com/kaKbBGM.jpeg', title: 'Atividade 10' },
  { id: 'top-11', url: 'https://i.imgur.com/4Tm4AUw.jpeg', title: 'Atividade 11' },
  { id: 'top-12', url: 'https://i.imgur.com/ubg448n.jpeg', title: 'Atividade 12' },
];

export const GALLERY_ROW_BOTTOM = [
  { id: 'bot-1', url: 'https://i.imgur.com/jB1HRoi.jpeg', title: 'Atividade 13' },
  { id: 'bot-2', url: 'https://i.imgur.com/nxqk0i0.jpeg', title: 'Atividade 14' },
  { id: 'bot-3', url: 'https://i.imgur.com/P17h1A6.jpeg', title: 'Atividade 15' },
  { id: 'bot-4', url: 'https://i.imgur.com/jSUiGF5.jpeg', title: 'Atividade 16' },
  { id: 'bot-5', url: 'https://i.imgur.com/NK1V3TZ.jpeg', title: 'Atividade 17' },
  { id: 'bot-6', url: 'https://i.imgur.com/5URqn1p.jpeg', title: 'Atividade 18' },
  { id: 'bot-7', url: 'https://i.imgur.com/Fj8PVHU.jpeg', title: 'Atividade 19' },
  { id: 'bot-8', url: 'https://i.imgur.com/kT3s0Hp.jpeg', title: 'Atividade 20' },
  { id: 'bot-9', url: 'https://i.imgur.com/T0GQUbG.jpeg', title: 'Atividade 21' },
  { id: 'bot-10', url: 'https://i.imgur.com/XXwsrV2.jpeg', title: 'Atividade 22' },
  { id: 'bot-11', url: 'https://i.imgur.com/fArUiS8.jpeg', title: 'Atividade 23' },
  { id: 'bot-12', url: 'https://i.imgur.com/rbvYF5j.jpeg', title: 'Atividade 24' },
  { id: 'bot-13', url: 'https://i.imgur.com/CkVQUsx.jpeg', title: 'Atividade 25' },
];

export const BEFORE_AFTER = {
  headline: 'Como o nosso material transforma a sua rotina e ajuda você a ensinar seu filho em casa',
  before: {
    title: 'SEM MATERIAL ORGANIZADO',
    items: [
      'Sentir insegurança sobre como ensinar e por onde começar a alfabetização',
      'Procurar atividades avulsas na internet todos os dias sem um método claro',
      'Arquivos de baixa qualidade, confusos e com tarefas que desmotivam a criança',
      'Perder horas preciosas tentando planejar e improvisar conteúdos',
      'Estresse, cobranças desgastantes e a criança recorrendo ao vício em telas',
    ],
  },
  after: {
    title: 'COM O KIT DE ALFABETIZAÇÃO',
    items: [
      'Um roteiro passo a passo que guia você a educar o seu filho com facilidade em casa',
      'Rotina leve de apenas 15 a 20 minutos por dia que cria constância sem cansaço',
      'Atividades lúdicas em alta resolução (A4) que despertam o amor pelo aprendizado',
      'Autonomia para a criança avançar com segurança e aprender 3x mais rápido',
      'Mais tempo livre de qualidade, conexão afetiva e orgulho de ver seu filho evoluir',
    ],
  },
};

export const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'ESCOLHA',
    description: 'Escolha a opção ideal para a sua necessidade (Plano Básico ou Kit Completo recomendado).',
    badge: '1 minuto',
    bgTone: 'bg-[#EFF6FF]',
    borderColor: 'border-[#DBEAFE]',
    textColor: 'text-[#1E40AF]',
  },
  {
    step: '02',
    title: 'ACESSE',
    description: 'Após a confirmação segura do pagamento, receba imediatamente no seu e-mail o link para baixar os arquivos.',
    badge: 'Acesso Imediato',
    bgTone: 'bg-[#FDF2F8]',
    borderColor: 'border-[#FCE7F3]',
    textColor: 'text-[#9D174D]',
  },
  {
    step: '03',
    title: 'IMPRIMA',
    description: 'Abra no computador ou celular e imprima apenas as páginas que você deseja usar naquele dia ou semana.',
    badge: 'Quantas vezes quiser',
    bgTone: 'bg-[#FEFCE8]',
    borderColor: 'border-[#FEF08A]',
    textColor: 'text-[#854D0E]',
  },
  {
    step: '04',
    title: 'PRATIQUE',
    description: 'Sente com a criança por 15 a 20 minutos e acompanhe os progressos com leveza e diversão.',
    badge: 'Momento em Família',
    bgTone: 'bg-[#F0FDF4]',
    borderColor: 'border-[#DCFCE7]',
    textColor: 'text-[#166534]',
  },
];

export const BONUSES_DATA: BonusItem[] = [
  {
    id: 'bonus-1',
    number: '01',
    title: 'Módulo Sílaba Alfabético',
    description: 'Atividades práticas focadas em sílabas simples, junções silábicas e identificação sonora para facilitar a transição da letra para a sílaba.',
    format: 'Caderno de Atividades em PDF',
    category: 'BÔNUS',
    themeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    iconName: 'Sparkles',
    imageUrl: 'https://i.imgur.com/JQoFLOf.png',
  },
  {
    id: 'bonus-2',
    number: '02',
    title: 'Módulo Sílabas Complexas',
    description: 'Famílias silábicas avançadas (como CH, LH, NH, RR, SS, dígrafos e encontros consonantais) com exercícios lúdicos e visuais.',
    format: 'Caderno de Exercícios em PDF',
    category: 'BÔNUS',
    themeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    iconName: 'Brain',
    imageUrl: 'https://i.imgur.com/R8SMGd6.png',
  },
  {
    id: 'bonus-3',
    number: '03',
    title: 'Módulo Pré-Silábicos',
    description: 'Exercícios de consciência fonológica, percepção auditiva e rimas para crianças que estão iniciando a relação entre grafia e som.',
    format: 'Material Imprimível em Alta Resolução',
    category: 'BÔNUS',
    themeColor: 'bg-amber-50 text-amber-800 border-amber-200',
    iconName: 'Palette',
    imageUrl: 'https://i.imgur.com/8peKkls.png',
  },
  {
    id: 'bonus-4',
    number: '04',
    title: 'Formação de Palavras & Pequenas Leituras',
    description: 'Atividades progressivas para formar as primeiras palavras, frases curtas e historinhas ilustradas desenvolvendo a fluência leitora.',
    format: 'Caderno Digital em PDF',
    category: 'BÔNUS',
    themeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    iconName: 'BookOpen',
    imageUrl: 'https://i.imgur.com/yqW5hIJ.png',
  },
  {
    id: 'bonus-5',
    number: '05',
    title: 'Canções Infantis para Cantar e Colorir',
    description: 'Letras ilustradas de cantigas de roda e canções educativas para a criança cantar, colorir e acelerar a memorização de forma divertida.',
    format: 'Coletânea Musical Ilustrada em PDF',
    category: 'BÔNUS',
    themeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    iconName: 'Music',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'basic',
    name: 'PLANO BÁSICO',
    badge: 'OPÇÃO BÁSICA',
    badgeType: 'subtle',
    price: 'R$ 12,90',
    priceValue: 12.9,
    periodText: 'Pagamento único • Sem mensalidades',
    description: 'Ideal para quem busca uma introdução prática e atividades fundamentais de alfabetização.',
    features: [
      { text: 'Caderno de Atividades Básicas em PDF (A4)', included: true },
      { text: 'Reconhecimento das Letras do Alfabeto (A ao Z)', included: true },
      { text: 'Treino de Caligrafia e Coordenação Motora Fina', included: true },
      { text: 'Atividades com Vogais e Primeiras Consoantes', included: true },
      { text: 'Arquivos em Alta Resolução Prontos para Imprimir', included: true },
      { text: 'Acesso Imediato após a confirmação', included: true },
    ],
    ctaText: 'QUERO O PLANO BÁSICO - R$ 12,90',
    checkoutUrl: 'https://checkout.applyfy.com.br/checkout/cmt5y7osn0q7901og8uoi1m1b?offer=O69QM30',
    isPopular: false,
  },
  {
    id: 'complete',
    name: 'KIT COMPLETO',
    badge: 'A ESCOLHA MAIS COMPLETA & RECOMENDADA',
    badgeType: 'highlight',
    price: 'R$ 24,90',
    priceValue: 24.9,
    originalPrice: 'R$ 75,90',
    discountBadge: '67% OFF',
    periodText: 'Pagamento único • Acesso vitalício aos arquivos',
    subheadline: 'Coleção Completa + 5 Super Bônus Exclusivos',
    description: 'A coleção definitiva para acompanhar todas as etapas do aprendizado da leitura e escrita com o melhor custo-benefício.',
    features: [
      { text: 'Coleção Completa de Alfabetização em Alta Resolução (PDF)', included: true, highlight: true },
      { text: 'Tudo do Plano Básico (Alfabeto A a Z, Caligrafia e Coordenação)', included: true },
      { text: '🎁 BÔNUS 1: Módulo Sílaba Alfabético (Sílabas simples, junções e sons)', included: true, highlight: true },
      { text: '🎁 BÔNUS 2: Módulo Sílabas Complexas (Famílias silábicas avançadas: CH, LH, NH, etc.)', included: true, highlight: true },
      { text: '🎁 BÔNUS 3: Módulo Pré-Silábicos (Consciência fonológica e treino auditivo)', included: true, highlight: true },
      { text: '🎁 BÔNUS 4: Formação de Palavras, Frases e Leituras Guiadas', included: true, highlight: true },
      { text: '🎁 BÔNUS 5: Canções Infantis (Cantigas para pintar e cantar)', included: true, highlight: true },
      { text: 'Garantia Incondicional de 7 Dias (Risco Zero)', included: true },
      { text: 'Acesso Vitalício + Atualizações Futuras', included: true },
    ],
    ctaText: 'QUERO O KIT COMPLETO - R$ 24,90',
    checkoutUrl: 'https://checkout.applyfy.com.br/checkout/cmt5y7osn0q7901og8uoi1m1b?offer=O5MDLW9',
    isPopular: true,
  },
];

export const FAQ_DATA: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'Como recebo o material após a compra?',
    answer: 'A entrega é 100% digital e imediata. Assim que o pagamento for confirmado pela plataforma de checkout segura, você receberá automaticamente um e-mail com o link exclusivo para acessar e baixar todos os arquivos em PDF no seu celular, tablet ou computador.',
  },
  {
    id: 'faq-2',
    question: 'O produto é físico ou digital?',
    answer: 'O produto é 100% digital (arquivos em PDF em alta resolução). Isso significa que você não paga frete, não precisa esperar dias pelos correios e pode imprimir na sua impressora caseira ou gráfica rápida quantas vezes desejar.',
  },
  {
    id: 'faq-3',
    question: 'Preciso imprimir tudo de uma vez?',
    answer: 'Não! Você tem total flexibilidade para imprimir apenas as páginas que for utilizar no dia ou na semana. Os arquivos são organizados por módulos para que você localize facilmente cada categoria.',
  },
  {
    id: 'faq-4',
    question: 'Para qual faixa etária o material é indicado?',
    answer: 'As atividades foram estruturadas especialmente para crianças de 4 a 10 anos de idade, abrangendo desde o reconhecimento de letras e sílabas até a formação de palavras, escrita e leitura de maneira leve, progressiva e sem cobranças excessivas.',
  },
  {
    id: 'faq-5',
    question: 'Qual a diferença entre o Plano Básico e o Kit Completo?',
    answer: 'O Plano Básico (R$ 12,90) entrega as atividades fundamentais introdutórias de alfabeto e traçado. O Kit Completo (R$ 24,90) inclui todos os módulos avançados (sílabas, pequenas leituras, jogos lúdicos) mais os 5 bônus exclusivos.',
  },
  {
    id: 'faq-6',
    question: 'Como funciona o acesso? Tem mensalidade?',
    answer: 'Não existe nenhuma mensalidade. É um pagamento único. Você baixa os arquivos em PDF para o seu dispositivo e eles ficam salvos com você para sempre.',
  },
  {
    id: 'faq-7',
    question: 'Como funciona a garantia de 7 dias?',
    answer: 'Você pode acessar os arquivos, verificar a qualidade e testar com a criança. Se por qualquer motivo não ficar satisfeito, basta solicitar o cancelamento dentro de 7 dias da compra na plataforma de pagamento para receber 100% do seu dinheiro de volta.',
  },
  {
    id: 'faq-8',
    question: 'Posso imprimir o material novamente se a criança quiser refazer?',
    answer: 'Sim! Uma das grandes vantagens do formato digital é que você pode reimprimir qualquer folha de atividade quantas vezes quiser para praticar novamente ou para usar com outros irmãos.',
  },
];

export const RELATOS_IMAGENS_DATA: RelatoImageItem[] = [
  {
    id: 'relato-1',
    author: 'Relato 1',
    role: 'Experiência Materna • Rotina em Casa',
    tag: 'Evolução e Foco',
    imageUrl: 'https://i.imgur.com/HHvku3a.jpeg',
    previewSnippet: 'Relato real de mãe acompanhando a alfabetização do filho.',
    rating: 5,
  },
  {
    id: 'relato-2',
    author: 'Relato 2',
    role: 'Experiência Paterna • Apoio e Autonomia',
    tag: 'Autonomia na Leitura',
    imageUrl: 'https://i.imgur.com/ZBzzjUZ.jpeg',
    previewSnippet: 'Relato real de pai incentivando o gosto pela leitura.',
    rating: 5,
  },
  {
    id: 'relato-3',
    author: 'Relato 3',
    role: 'Professora Alfabetizadora • Ed. Infantil',
    tag: 'Prática Pedagógica',
    imageUrl: 'https://i.imgur.com/sroSxDn.jpeg',
    previewSnippet: 'Relato de educadora utilizando o material em sala de aula.',
    rating: 5,
  },
  {
    id: 'relato-4',
    author: 'Relato 4',
    role: 'Mãe e Apoio Escolar',
    tag: 'Menos Telas, Mais Aprendizado',
    imageUrl: 'https://i.imgur.com/444QljC.jpeg',
    previewSnippet: 'Relato de mãe sobre a redução do tempo de telas.',
    rating: 5,
  },
  {
    id: 'relato-5',
    author: 'Relato 5',
    role: 'Reforço Escolar e Família',
    tag: 'Coordenação e Escrita',
    imageUrl: 'https://i.imgur.com/j49UvcU.jpeg',
    previewSnippet: 'Relato de evolução motora e fixação do aprendizado.',
    rating: 5,
  },
];



